Repository vmware-tanzu/crash-diagnostics, pull requests merged in 2020-07, with the labels that each got.

#97 Starlark - Implement command function `run_local()`
  starlark/run_local.go
  starlark/run_local_test.go
  starlark/starlark_exec.go
  starlark/support.go
Labels: cla-not-required

#101 Starlark - Implementation of the capture_local function
  starlark/capture.go
  starlark/capture_local.go
  starlark/capture_local_test.go
  starlark/starlark_exec.go
  starlark/support.go
Labels: cla-not-required

#96 Adds kube_nodes_provider() starlark built-in
  k8s/search_params.go
  starlark/kube_get.go
  starlark/kube_nodes_provider.go
  starlark/kube_nodes_provider_test.go
  starlark/resources.go
  starlark/resources_kube_nodes_provider_test.go
  starlark/starlark_exec.go
  starlark/support.go
Labels: cla-not-required

#109 Starlark - Better argument handling with `starlark.UnpackArgs`
  ssh/scp.go
  starlark/capture.go
  starlark/capture_local.go
  starlark/copy_from.go
  starlark/crashd_config.go
  starlark/crashd_config_test.go
  starlark/hostlist_provider.go
  starlark/hostlist_provider_test.go
  starlark/kube_config.go
  starlark/resources.go
  starlark/resources_test.go
  starlark/run.go
  starlark/ssh_config.go
  starlark/ssh_config_test.go
  starlark/starlark_exec.go
  starlark/starlark_exec_test.go
Labels: api-update, cla-not-required

#111 Implementation of the archive script function
  starlark/archive.go
  starlark/archive_test.go
  starlark/crashd_config_test.go
  starlark/starlark_exec.go
  starlark/support.go
Labels: cla-not-required

#112 Starlark script example and tests
  examples/host-list-provider.star
  examples/kind-api-objects.star
  examples/kind-capi-bootstrap.star
  examples/kube-nodes-provider.star
  examples/pod-logs.star
  examples/script-args.star
  exec/executor_test.go
  ssh/main_test.go
  starlark/capture_test.go
  starlark/copy_from_test.go
  starlark/os_builtins.go
  starlark/run_local.go
  starlark/run_test.go
  testing/setup.go
Labels: api-update, cla-not-required

#114 Resource provider for CAPV
  cmd/run.go
  examples/capv_provider.file
  k8s/client.go
  k8s/kube_config.go
  k8s/nodes.go
  k8s/search_params.go
  k8s/search_params_test.go
  provider/kube_config.go
  starlark/archive.go
  starlark/capv_provider.go
  starlark/kube_capture.go
  starlark/kube_config.go
  starlark/kube_config_test.go
  starlark/kube_get.go
  starlark/kube_nodes_provider.go
  starlark/resources.go
  starlark/run.go
  starlark/starlark_exec.go
  starlark/support.go
Labels: api-update, cla-not-required

#120 Unpacking kube directive arguments via Starlark library function
  starlark/kube_capture.go
  starlark/kube_capture_test.go
  starlark/kube_config.go
  starlark/kube_get.go
  starlark/kube_get_test.go
  starlark/kube_nodes_provider.go
Labels: cla-not-required

#121 Adds meaningful constructor name to starlark structs
  exec/executor.go
  k8s/search_result.go
  starlark/crashd_config.go
  starlark/govalue.go
  starlark/govalue_test.go
  starlark/hostlist_provider.go
  starlark/kube_capture.go
  starlark/kube_config.go
  starlark/kube_get.go
  starlark/kube_nodes_provider.go
  starlark/os_builtins.go
  starlark/resources.go
  starlark/run.go
  starlark/ssh_config.go
  starlark/starlark_exec.go
  starlark/support.go
Labels: api-update, cla-not-required

#124 Adds the set_as_default directive
  examples/capv_provider.star
  examples/kind-api-objects.star
  examples/kind-capi-bootstrap.star
  examples/pod-logs.star
  examples/script-args.star
  starlark/capture_test.go
  starlark/copy_from_test.go
  starlark/hostlist_provider_test.go
  starlark/kube_capture_test.go
  starlark/kube_config.go
  starlark/kube_config_test.go
  starlark/kube_get_test.go
  starlark/kube_nodes_provider_test.go
  starlark/resources.go
  starlark/resources_kube_nodes_provider_test.go
  starlark/resources_test.go
  starlark/set_as_default.go
  starlark/set_as_default_test.go
  starlark/ssh_config.go
  starlark/ssh_config_test.go
  starlark/starlark_exec.go
  starlark/support.go
Labels: cla-not-required

#129 Fix UnpackArgs inputs for kube functions
  starlark/kube_capture.go
  starlark/kube_config.go
  starlark/kube_get.go
  starlark/kube_nodes_provider.go
Labels: cla-not-required, code-reorg

#132 Changes tests to use provided ssh key pair
  .github/workflows/compile-test.yaml
  examples/kube-nodes-provider.star
  exec/executor_test.go
  ssh/scp_test.go
  ssh/ssh_test.go
  ssh/test_support.go
  starlark/capture_test.go
  starlark/copy_from_test.go
  starlark/main_test.go
  starlark/run_test.go
  testing/setup.go
  testing/sshserver.go
Labels: cla-not-required, code-reorg

#134 Change set_as_default directive
  examples/capv_provider.star
  examples/kind-api-objects.star
  examples/pod-logs.star
  starlark/capture_test.go
  starlark/copy_from_test.go
  starlark/kube_capture_test.go
  starlark/kube_get_test.go
  starlark/resources_kube_nodes_provider_test.go
  starlark/resources_test.go
  starlark/run_test.go
  starlark/set_as_default.go
  starlark/set_as_default_test.go
  starlark/set_defaults.go
  starlark/set_defaults_test.go
  starlark/ssh_config_test.go
  starlark/starlark_exec.go
  starlark/support.go
Labels: api-update, cla-not-required
