Repository vmware-tanzu/crash-diagnostics, pull requests merged in 2020-08, with the labels that each got.

#130 Document update for the version 0.3.0
  README.md
  ROADMAP.md
  TODO.md
  docs/README.md
Labels: cla-not-required

#135 Replaces named flag with positional argument
  cmd/run.go
Labels: api-update, cla-not-required

#138 Updates the CLI name to crashd
  cmd/crash-dianostics.go
  docs/README.md
  starlark/capa_provider.go
  starlark/capv_provider.go
  starlark/kube_config.go
  starlark/kube_config_test.go
Labels: api-update, cla-not-required

#142 Update extensions for example scripts
  examples/capa_provider.crsh
  examples/capv_provider.crsh
  examples/host-list-provider.crsh
  examples/kind-api-objects.crsh
  examples/kind-capi-bootstrap.crsh
  examples/kube-nodes-provider.crsh
  examples/pod-logs.crsh
  examples/script-args.crsh
  exec/executor_test.go
Labels: cla-not-required, code-reorg

#145 Fixing example scripts in tests
  examples/kind-api-objects.crsh
  examples/kind-capi-bootstrap.crsh
  exec/executor_test.go
Labels: cla-not-required

#149 Reverts using custom ssh keypair for tests
  .github/workflows/compile-test.yaml
  examples/kube-nodes-provider.crsh
  ssh/scp_test.go
  ssh/ssh_test.go
  ssh/test_support.go
  starlark/capture_test.go
  starlark/copy_from_test.go
  starlark/main_test.go
  starlark/run_test.go
  testing/setup.go
  testing/sshserver.go
Labels: cla-not-required

#151 E2E Tests Fixes
  .github/workflows/compile-test.yaml
  .gitignore
  examples/host-list-provider.crsh
  examples/kube-nodes-provider.crsh
  exec/executor_test.go
  k8s/main_test.go
  ssh/client.go
  ssh/client_test.go
  ssh/main_test.go
  ssh/scp.go
  ssh/scp_test.go
  ssh/ssh_test.go
  ssh/test_support.go
  starlark/capture_test.go
  starlark/copy_from_test.go
  starlark/kube_capture_test.go
  starlark/main_test.go
  starlark/run_test.go
  starlark/starlark_suite_test.go
  testing/id_rsa
  testing/id_rsa.pub
  testing/key.go
  testing/keys/id_rsa
  testing/keys/id_rsa.pub
  testing/kindcluster.go
  testing/setup.go
  testing/sshserver.go
Labels: cla-not-required

#152 Changes ssh command string for proxy args
  ssh/ssh.go
  ssh/ssh_test.go
Labels: cla-not-required

#154 Fixes example for the args flag of the run command
  README.md
Labels: cla-not-required, documentation

#160 Generate static SSH test keys
  testing/id_rsa
  testing/id_rsa.pub
  testing/key.go
  testing/setup.go
Labels: cla-not-required

#161 Goreleaser generated binary name update
  .github/workflows/deploy.yaml
  .goreleaser.yml
  go.sum
Labels: cla-not-required

#164 Adds `--args-file` flag to crashd run command
  cmd/cmd_suite_test.go
  cmd/run.go
  cmd/run_test.go
  util/args.go
  util/args_test.go
  util/util_suite_test.go
Labels: cla-not-required
